### ISSUE TITLE
[Bug] Style conflict in dark mode

### ISSUE THREAD

**Issue by wibus-wee** [wibus-wee/icalingua-theme-telegram#21]
<sup>**Origin message**: https://t.me/Icalinguapp/19467</sup>

## 分析

这个是我编写 CSS 的时候犯的一点小错误，但是现在看我也并不知道如何解决这个问题。

首先是似乎在切换模式的时候，没有 className 的变化，而是 element.style 进行了变化，但是这部分是可以被自定义的，也就是说我没有办法使用 `===` 来判断目前是什么状态。

还有一个解决办法就是直接读取 `config.yaml`，但是这个又有一个问题，有人可能是自定义的 config.yaml 路径，我也没有办法直接像读取 addon.js 路径来获取到 config.yaml 的目录。虽然写死也是可以的，但是这会直接禁止掉自定义配合文件的用户使用

**Comment by dmlgzs** [comment]
```javascript
await require('electron').ipcRenderer.invoke('getSettings')
```
这个可以获取配置

**Comment by wibus-wee** [comment]
其实能用 😂 （忘记有这个东西了）

**Comment by dmlgzs** [comment]
> 其实能用 😂 （忘记有这个东西了）

打开图片可以用
```javascript
require('electron').ipcRenderer.send('openImage', url)
```

**Comment by wibus-wee** [comment]
> 另外打开图片可以用
> 
> ```js
> require('electron').ipcRenderer.send('openImage', url)
> ```

🆒 thanks!

**Comment by wibus-wee** [comment]
不过我后面应该会重写一个查看器（直接把 tg 的 copy 过来）
