### ISSUE TITLE
[Bug] 表情和时间戳重叠

### ISSUE THREAD

**Issue by Eletary** [wibus-wee/icalingua-theme-telegram#22]
### Describe the bug

![image](https://github.com/wibus-wee/icalingua-theme-telegram/assets/86780576/765f786a-8bca-4514-8b4c-359f63ec9741)

### Reproduction

在群里发送三个拜谢，用另一个帐号查看消息

### System Info

```Shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 4.92 GB / 15.25 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.2 - /usr/bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
这似乎还是之前 #2 的问题，我研究一下怎么改好一点，谢谢🙏
