### ISSUE TITLE
[Bug] 消息多选时自己的消息无高亮，且无法框选单张图片

### ISSUE THREAD

**Issue by Eletary** [wibus-wee/icalingua-theme-telegram#29]
### Describe the bug

框选单张图片无效果，也无法选中

![image](https://github.com/wibus-wee/icalingua-theme-telegram/assets/86780576/cd8ed8b9-8361-43b5-bf9b-d39441f26741)

### Reproduction

框选自己的消息/框选图片

### System Info

```Shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 4.92 GB / 15.25 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.2 - /usr/bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
fixed.
