### ISSUE TITLE
[Bug] 链接高亮不改颜色，导致合并转发消息不明显

### ISSUE THREAD

**Issue by Eletary** [wibus-wee/icalingua-theme-telegram#30]
### Describe the bug

![image](https://github.com/wibus-wee/icalingua-theme-telegram/assets/86780576/403eef70-2116-4aa8-af60-22c3a957aa43)

### Reproduction

发送合并转发消息

### System Info

```Shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 4.92 GB / 15.25 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.2 - /usr/bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
fixed. 我给它加上了下划线
