### ISSUE TITLE
[Bug] 合并转发消息显示问题

### ISSUE THREAD

**Issue by LockRim** [wibus-wee/icalingua-theme-telegram#35]
### Describe the bug

![image](https://github.com/wibus-wee/icalingua-theme-telegram/assets/52944370/174717c7-17a5-416a-bdb2-94cecbfdf2a2)

### Reproduction

主题dark，打开合并转发消息

### System Info

```Shell
System:
    OS: Linux 6.4 Arch Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 8.48 GB / 15.37 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.2.0 - /run/user/1000/fnm_multishells/8142_1691666298239/bin/node
    Yarn: 1.22.19 - /run/user/1000/fnm_multishells/8142_1691666298239/bin/yarn
    npm: 8.9.0 - /run/user/1000/fnm_multishells/8142_1691666298239/bin/npm
    pnpm: 8.6.12 - /usr/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
ok
will be fixed (1 week)

**Comment by wibus-wee** [comment]
你可以直接下载 https://github.com/wibus-wee/icalingua-theme-telegram/releases/download/ci/icalingua-theme-telegram-20230826-d49f9b.zip 来获取修复版本

感谢反馈
